auto_save: true
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
add_point: false
single_class: false
delete_popup: true
display_label_option: true
display_probability_option: true
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

labels_class:
  outdoor_segmentation:
    ['pattern-block', 'non-pattern-block', 'curb', 'braille-block', 'cement', 'asphalt',
    'cross-walk', 'speed-bump', 'sand', 'bicycle-road', 'deck', 'grass', 'pebble', 'void']
  outdoor_detection:
    ['person', 'car', 'truck', 'bus', 'motorcycle', 'bicycle', 'kickboard',
    'robot', 'animal', 'mailbox', 'traffic-sign', 'unknown',
    'stop', 'walk', 'light-out', 'countdown-walk', 'countdown-light-out']
  indoor_segmentation:
    ['in_panel', 'out_panel', 'rect-btn', 'circle-btn', 'ellipse-btn', 'rect-circle-btn', 'rect-rect-btn', 'special-btn',
    'sticker', 'admin-key', 'indicator', 'handi-symbol', 'screw', 'others']

default_shape_color: [0, 0, 255]
shape_color: manual  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors:
  pattern-block: [0, 102, 0]  # outdoor_segmentation
  non-pattern-block: [204, 255, 204]
  curb : [102, 102, 255]
  braille-block : [255, 255, 0]
  cement : [51, 204, 204]
  asphalt : [204, 51, 51]
  cross-walk : [64, 255, 0]
  speed-bump : [153, 102, 0]
  sand : [102, 0, 153]
  bicycle-road : [204, 51, 204]
  deck : [255, 165, 0]
  grass : [252, 107, 3]
  pebble : [0, 128, 128]
  void : [0, 0, 0]
  person: [252, 107, 3]  # outdoor_detection
  bicycle: [128, 0, 0]
  motorcycle : [0, 128, 0]
  kickboard : [128, 128, 0]
  robot : [0, 0, 128]
  animal : [102, 0, 153]
  mailbox : [128, 0, 128]
  car : [0, 128, 128]
  bus : [128, 128, 128]
  truck : [64, 0, 0]
  stop : [192, 0, 0]
  walk : [64, 128, 0]
  light-out : [51, 204, 204]
  countdown-walk : [255, 165, 0]
  countdown-light-out : [153, 102, 0]
  traffic-sign : [64, 0, 128]
  unknown : [204, 255, 204]
  in_panel : [128, 128, 128] # indoor_segmentation
  out_panel : [192, 192, 192]
  rect-btn : [255, 0, 0]
  circle-btn : [0, 255, 0]
  ellipse-btn : [200, 100, 50]
  rect-circle-btn : [255, 255, 0]
  rect-rect-btn : [0, 255, 255]
  special-btn : [255, 0, 255]
  sticker : [128, 0, 0]
  admin-key : [128, 128, 0]
  indicator : [0, 128, 0]
  handi-symbol : [128, 0, 128]
  screw : [0, 128, 128]
  others : [100, 200, 150]

shape:
  # drawing
  line_color: [192, 217, 0, 128]
  fill_color: [192, 217, 0, 0]  # transparent
  vertex_fill_color: [192, 217, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: true

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D, down, right]
  open_prev: [A, Ctrl+Shift+A, up, left]

  hide_all: Ctrl+H
  show_all: Ctrl+G

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: [Delete, Q]
  duplicate_polygon: Ctrl+D
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  redo: Ctrl+Shift+Z
  undo: Ctrl+Z
  undo_last_point: Ctrl+Z
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  edit_label_name: E
  toggle_keep_prev_mode: Ctrl+P
  toggle_add_points_mode: Ctrl+B
  single_class_mode: Ctrl+Shift+B
  keep_brightness_contrast: Ctrl+K
  display_label_name: Ctrl+L
  remove_selected_point: [Meta+H, Backspace]
  set_brightness_contrast: Ctrl+M
  set_prev_brightness_contrast: Z

  check_labels: Ctrl+/
  delete_popup: Ctrl+Shift+Q
